### ISSUE TITLE
Реализовать получение списка пользователей

### ISSUE THREAD

**Issue by LupusAnay** [henculus/blog#12]
Реализовать метод https://github.com/henculus/blog-rust/blob/996819b9c16b7a014f61b181fe5c619f6b070e6b/src/users_view.rs#L12

Который будет возвращать пользователю с ролью "админ" список пользователей

**Comment by SarielAki** [comment]
В админах на данный момент нет необходимости, поэтому метод будет возвращать список любому пользователю
