### ISSUE TITLE
Реализовать удаление пользователя

### ISSUE THREAD

**Issue by LupusAnay** [henculus/blog#15]
https://github.com/henculus/blog-rust/blob/996819b9c16b7a014f61b181fe5c619f6b070e6b/src/users_view.rs#L34

Реализовать метод, который будет удалять пользователя, может быть выполнен либо пользователем с ролью admin, либо самим пользователем

**Comment by SarielAki** [comment]
Так как роль admin пока не нужна, только сам пользователь будет удалять себя из базы
