### ISSUE TITLE
Реактивность? при выходе из аккаунта

### ISSUE THREAD

**Issue by LupusAnay** [henculus/blog#97]
На данный момент после того как выходишь из аккаунта в списке статей продолжают отображаться неопубликованные статьи, при переходе на которые происходит бесконечная загрузка. Возможно стоит добавить хук на изменение стейта isLoggedIn для рендера списка статей

**Comment by RanetkaGod** [comment]
Это я знаю, у меня пока вообще нет разделения на паблишед и не паблишед посты, просто точно ещё не знаю как у нас будет реализован список неопубликованных статей (в отдельном пункте меню или прямо в общем списке статей)
Потому как необходимость вывода неопубликованных статей в общем фиде весьма спорная тема, учитывая что статьи в данный момент выдаются по дате написания
